import assert from 'node:assert/strict';
import {spanishDesignBrief,validSupremeDesign,readiness,SUPREME_SCHEMA} from './supreme-recipe-v9.mjs';
const original=spanishDesignBrief('Quiero armadura Nightfall negra violeta con casco Kage Oni para ambos Hunters');
assert.equal(original.style,'nightfall');
assert.equal(original.body,'nightfall');
assert.equal(original.head,'kage-oni');
assert.equal(original.variant,'both');
assert.equal(original.colors.primary,'#101118');
const state=readiness(original);
assert.equal(state.designOnly,true);
assert.equal(state.aiModelConnected,false);
assert.equal(state.gameWritable,false);
assert.equal(state.readyForPremiumExport,false);
assert(state.remaining.includes('COMBINAR_EXPORTS_V6_V8_Y_VALIDAR_BIND_PENDIENTE'));
const idea=spanishDesignBrief('Armadura samurái original negro violeta con máscara de oni y capa épica');
assert.equal(idea.style,'samurai');
assert.equal(idea.body,'new-design-needed');
assert.equal(idea.head,'kage-oni');
assert(readiness(idea).remaining.includes('NUEVA_ARMADURA_CORPORAL_3D_PENDIENTE'));
const female=spanishDesignBrief('Ninja para mujer sin casco, detalles carmesí');
assert.equal(female.variant,'female');
assert.equal(female.head,'none');
assert.equal(female.colors.accent,'#a01d38');
assert.throws(()=>spanishDesignBrief(''),/BRIEF_REJECTED/);
assert.throws(()=>validSupremeDesign({...original,script:'os.system("rm -rf /")'}),/SUPREME_DESIGN_UNSAFE_OBJECT/);
assert.throws(()=>validSupremeDesign({...original,rig:'fake'}),/SUPREME_SOURCE_MISMATCH/);
assert.throws(()=>validSupremeDesign({...original,requestedSlots:['head','head']}),/INVALID_ARMOR_SLOTS/);
assert.throws(()=>validSupremeDesign({...original,colors:{...original.colors,primary:'<script>'}}),/INVALID_COLOR_PALETTE/);
assert.throws(()=>validSupremeDesign(JSON.parse('{"schema":"'+SUPREME_SCHEMA+'","__proto__":{"gameState":true}}')),/SUPREME_DESIGN_UNSAFE_OBJECT/);
console.log('HIGHFLY_SUPREME_V9_SAFE_SPANISH_TO_STRUCTURED_DESIGN_GREEN=1 AI_API_CONNECTED=0 NO_ARBITRARY_SCRIPT=1 NO_GAME_WRITES=1');
