import assert from 'node:assert/strict';
import {SOURCE,SLOTS,PALADIN,validateKit,originalPaladinKit,replaceEquipmentSlot,returnToOriginal,composeEquipmentPlan,makeReforgeRecipe} from './skin7-native-wardrobe.mjs';
assert.equal(SOURCE.bones,23);
assert.equal(SLOTS.length,7);
assert.equal(Object.values(PALADIN).flat().length,11);
const kit=originalPaladinKit();
assert.equal(kit.equipment.head.nodes[0],'Armor_paladin_Head');
const originalM=composeEquipmentPlan(kit,'M'),originalF=composeEquipmentPlan(kit,'F');
assert.equal(originalM.activeEquipmentNodes.length,11);
assert.equal(originalF.activeEquipmentNodes.length,11);
assert.equal(originalM.keepOriginalBodyNodes.length,10);
assert(originalF.keepUndergarmentNodes.includes('F_Top'));
assert(!originalM.keepUndergarmentNodes.includes('M_Loin'));
assert(!originalF.keepUndergarmentNodes.includes('F_Loin'));
assert(originalM.suppressUnderFullHelmet.includes('ear'));
assert(originalM.keepFacialFeatures.includes('eye'));
assert.equal(originalM.noGameDeploy,true);
const changed=replaceEquipmentSlot(kit,'arms',['HF7RF_PALADIN_ARM_L_LEGEND','HF7RF_PALADIN_ARM_R_LEGEND']);
const variant=composeEquipmentPlan(changed,'M');
assert(variant.activeEquipmentNodes.includes('HF7RF_PALADIN_ARM_L_LEGEND'));
assert(!variant.activeEquipmentNodes.includes('Armor_paladin_ArmL'));
assert(variant.activeEquipmentNodes.includes('Armor_paladin_Chest'));
assert(!kit.equipment.arms.nodes.some(x=>x.startsWith('HF7RF_')));
assert.equal(variant.keepOriginalBodyNodes.length,10);
const reverted=returnToOriginal(changed,'arms');
assert.deepEqual(reverted.equipment.arms.nodes,PALADIN.arms);
assert.deepEqual(composeEquipmentPlan(reverted,'M'),originalM);
assert.throws(()=>replaceEquipmentSlot(kit,'arms',['HFV19_M_ARMS_TINY_FLOATING_SPIKE']),/FORGED_NODE_INVALID/);
assert.throws(()=>replaceEquipmentSlot(kit,'horns',['HF7RF_PALADIN_HORN']),/BAD_SLOT/);
assert.throws(()=>validateKit({...kit,nativeJointCount:24}),/ORIGINAL_RIG_ONLY/);
const recipe=makeReforgeRecipe({kit,slot:'arms',shape:{width:1.32,curvature:.4,edgeThickness:.024},
 reference:'Ensanchar hombreras de paladín original; reforjar curva y borde, no superponer Nightfall.'});
assert.deepEqual(recipe.nativeSourceMeshNames,PALADIN.arms);
assert.equal(recipe.edit.width,1.32);
assert.equal(recipe.artistApproved,false);
assert.equal(recipe.newGeometryRequired,true);
assert.throws(()=>makeReforgeRecipe({kit,slot:'arms',shape:{width:8}}),/UNSAFE_REFORGE_SHAPE/);
assert.throws(()=>makeReforgeRecipe({kit,slot:'head',shape:{unverifiedAI:999}}),/UNKNOWN_SHAPE_CONTROL/);
const recipeHead=makeReforgeRecipe({kit,slot:'head',shape:{height:1.12,depth:1.08,flare:.22}});
assert.deepEqual(recipeHead.nativeSourceMeshNames,['Armor_paladin_Head']);
console.log('HIGHFLY_SKIN7_NATIVE_PALADIN_SEVEN_SLOT_WARDROBE_ORIGINAL_BODY_AND_TRUE_EQUIPMENT_REPLACEMENT_GREEN=1');
console.log('HIGHFLY_SKIN7_PALADIN_REFORGE_RECIPE_KEEPS_ACTUAL_SOURCE_GEOMETRY_GREEN=1');
